name: pipelines
channels:
  - defaults
dependencies:
  - python=3.12.2
  - python-dotenv
  - aiohttp
  - tzlocal
  - boto3
  - PyJWT
  - pip=23.3.1
  - pip:
    - jsonpath-ng
    - pinecone-client
    - llama-index
    - llama-index-readers-json
    - llama-index-vector-stores-pinecone
